
/** List of Client */
export const GET_PROFILE_LIST_REQUEST = 'GET_PROFILE_LIST_REQUEST';
export const SET_PROFILE_LIST_REQUEST = 'SET_PROFILE_LIST_REQUEST';
export const SET_PROFILE_IMAGE_REQUEST = 'SET_PROFILE_IMAGE_REQUEST';
export const GET_PROFILE_IMAGE_REQUEST = 'GET_PROFILE_IMAGE_REQUEST';


