
/** List of Client */
export const GET_NOTIFY_LIST_REQUEST = 'GET_NOTIFY_LIST_REQUEST';
export const SET_NOTIFY_LIST_REQUEST = 'SET_NOTIFY_LIST_REQUEST';

/** List of Client */
export const GET_NEW_NOTIFY_LIST_REQUEST = 'GET_NEW_NOTIFY_LIST_REQUEST';
export const SET_NEW_NOTIFY_LIST_REQUEST = 'SET_NEW_NOTIFY_LIST_REQUEST';

