
/** List of Client */
export const GET_REQUIREMENT_LIST_REQUEST = 'GET_REQUIREMENT_LIST_REQUEST';
export const SET_REQUIREMENT_LIST_REQUEST = 'SET_REQUIREMENT_LIST_REQUEST';

//Create User
export const ADD_REQUIREMENT = 'ADD_REQUIREMENT';
export const ADD_REQUIREMENT_REQUEST = 'ADD_REQUIREMENT_REQUEST';
export const UPDATE_REQUIREMENT = 'UPDATE_REQUIREMENT'
export const DELETE_REQUIREMENT = 'DELETE_REQUIREMENT'


export const GET_REQUIREMENT_MODAL = 'GET_REQUIREMENT_MODAL';
export const HIDE_REQUIREMENT_MODAL = 'HIDE_REQUIREMENT_MODAL';
export const GET_REQUIREMENT_DELETE_MODAL = 'GET_REQUIREMENT_DELETE_MODAL';
export const HIDE_REQUIREMENT_DELETE_MODAL = 'HIDE_REQUIREMENT_DELETE_MODAL';


//error
export const GET_ERROR = 'GET_ERROR';